// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ml_schemas

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEf0b8645DecodeMlSchemas(in *jlexer.Lexer, out *LinearModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Coefficient":
			if in.IsNull() {
				in.Skip()
				out.Coefficient = nil
			} else {
				in.Delim('[')
				if out.Coefficient == nil {
					if !in.IsDelim(']') {
						out.Coefficient = make([]float64, 0, 8)
					} else {
						out.Coefficient = []float64{}
					}
				} else {
					out.Coefficient = (out.Coefficient)[:0]
				}
				for !in.IsDelim(']') {
					var v1 float64
					v1 = float64(in.Float64())
					out.Coefficient = append(out.Coefficient, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Intercept":
			out.Intercept = float64(in.Float64())
		case "Penalty":
			out.Penalty = string(in.String())
		case "Alpha":
			out.Alpha = float64(in.Float64())
		case "L1Ratio":
			out.L1Ratio = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEf0b8645EncodeMlSchemas(out *jwriter.Writer, in LinearModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Coefficient\":"
		out.RawString(prefix[1:])
		if in.Coefficient == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Coefficient {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Float64(float64(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Intercept\":"
		out.RawString(prefix)
		out.Float64(float64(in.Intercept))
	}
	{
		const prefix string = ",\"Penalty\":"
		out.RawString(prefix)
		out.String(string(in.Penalty))
	}
	{
		const prefix string = ",\"Alpha\":"
		out.RawString(prefix)
		out.Float64(float64(in.Alpha))
	}
	{
		const prefix string = ",\"L1Ratio\":"
		out.RawString(prefix)
		out.Float64(float64(in.L1Ratio))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LinearModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEf0b8645EncodeMlSchemas(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LinearModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEf0b8645EncodeMlSchemas(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LinearModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEf0b8645DecodeMlSchemas(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LinearModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEf0b8645DecodeMlSchemas(l, v)
}
